(define (squ x) (* x x))
(define (sum-square x y) (+ (squ x) (squ y)))
(define (largesum x y z)
  (if (< x y)
    (if (< x z)
      (sum-square y z)
      (sum-square x y))
    (if (< y z)
      (sum-square x z)
      (sum-square x y))))
